# SPDX-FileCopyrightText: 2022 - 2024 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:

  orthanc:
    image: orthancteam/orthanc:24.10.3
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    depends_on: [orthanc-db]
    restart: unless-stopped
    expose:
      - "8042"
    networks:
      - web
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthanc-localrouter.rule=Host(`local.pacs.ocb.msf.org`)"
      - "traefik.http.routers.orthanc-localrouter.entrypoints=websecure"
      - "traefik.http.routers.orthanc-localrouter.tls.certresolver=letsencrypt_dns"
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "false"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      # to use OHIF-plugin:  make sure to have a "OHIF" config and use "dicom-web" source
      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc",
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableShares": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "EnableOpenInOhifViewer3": true,
              // to use OHIF-plugin:  use http://localhost/orthanc/ohif/
              "OhifViewer3PublicRoot": "http://localhost/orthanc/ohif/",
              // "OhifViewer3PublicRoot": "http://localhost/ohif/"
              "ViewersIcons" : {                
                "ohif": "bi bi-grid",                
                "wsi": "fa-solid fa-microscope fa-button"
              },
              "ViewersOrdering" : [           
                "ohif",            
                "wsi"
              ]
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "ohif-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "http://localhost/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",           
            "StandardConfigurations" : [
              "orthanc-explorer-2",
              "ohif"
            ],
            "TokenHttpHeaders" : [ "api-key" ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          }, 
          "OHIF": {
            "DataSource": "dicom-web",
            "RouterBasename": "/orthanc/ohif/"
          }
        }


  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:24.11.0
    # always disable port mapping in production !!!
    # ports: ["8000:8000"]
    # permissions can be customized in the permissions.json file
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
    depends_on: [keycloak]
    networks:
      - web
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
      ENABLE_KEYCLOAK_API_KEYS: "true"
#      # to enable the permissions edition UI in OE2, you need to provide a KEYCLOAK_CLIENT_SECRET
#      KEYCLOAK_CLIENT_SECRET: "change-me-I-am-a-secret-you-get-in-keycloak-logs"
      KEYCLOAK_CLIENT_SECRET: "gl5UqdJ2T10fi66zMEwu9WRT2OoEqjbG" # this changes after every new initialization
      PUBLIC_ORTHANC_ROOT: "http://localhost/orthanc/"
      PUBLIC_LANDING_ROOT: "http://localhost/orthanc/ui/app/token-landing.html"
      PUBLIC_OHIF_ROOT: "http://localhost/orthanc/ohif/"
      USERS: |
        {
          "share-user": "change-me"
        }

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - db

  keycloak:
    image: ghcr.io/msf-ocb/msfocb-keycloak-docker/keycloak:latest
    depends_on: [keycloak-db]
    restart: unless-stopped
    networks:
      - web
      - db
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-localrouter.rule=Host(`local.kc.ocb.msf.org`)"
      - "traefik.http.routers.keycloak-localrouter.entrypoints=websecure"
      - "traefik.http.routers.keycloak-localrouter.tls.certresolver=letsencrypt_dns"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      #prod
      KC_HOSTNAME: "https://local.kc.ocb.msf.org/"
      KC_HOSTNAME_URL: "https://local.kc.ocb.msf.org/"
      KC_HOSTNAME_ADMIN_URL: "https://local.kc.ocb.msf.org/"
      #local
      # KC_HOSTNAME: "http://localhost/keycloak/"
      # KC_HOSTNAME_URL: "http://localhost/keycloak/"
      # KC_HOSTNAME_ADMIN_URL: "http://localhost/keycloak/"
    # volumes:
    #   - /home/bc/tmp:/usr/tmp

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db:

networks:
  db:
  web:
    external: true
